# Permalinks
permalink:   /:categories/:year/:month/:day/:title

# Setup
title:               Socrates Data Science Blog
#tagline:            'A Jekyll theme'   // Commented by SOC
description:         'In this Blog you will find evidence of my journey towards becoming a Data Scientist including the challenges I faced and addressed, Data Science competitions, tools, and tips & tricks. Contact me at <a href="https://twitter.com/ksocrates" target="_blank">@ksocrates</a> or <a href="mailto:socratesk@gmail.com?subject=Hi%20there!">Email me</a>.'
url:                 http://projects.socratesk.com
baseurl:             	''
urlimg: 			'assets/img/'


gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  
paginate:            5

# About/contact
author:
  name:              Socrates Krishnamurthy
  url:               https://twitter.com/ksocrates
  email:             socratesk@gmail.com
  avatar:			 socpix.JPG

# Custom vars
version:             1.0.0

  